"""Central metadata registry for every algorithm in the project.

Single source of truth used by:
  * /algorithms dashboard (complexity cards + measured timings),
  * Algorithm Lab selector,
  * README/docs tables,
  * the tests that assert every documented algorithm is implemented.

Nothing here executes an algorithm - it only *describes* it.  The measured
execution time is merged in at render time.
"""

from __future__ import annotations

ALGORITHMS: list[dict] = [
    # ---------------------------------------------------------------- search
    {
        "id": "linear_search",
        "name": "Linear Search",
        "category": "Searching",
        "purpose": "Find a key in an unsorted collection by scanning every element.",
        "input": "Unsorted list + target key",
        "output": "Index of first match, or not-found",
        "time": "O(n)",
        "space": "O(1)",
        "best": "O(1) - key is the first element",
        "average": "O(n) - key in the middle",
        "worst": "O(n) - key absent or last",
        "why": "Works on unsorted data with zero pre-processing; the honest baseline that justifies indexing.",
        "used_for": "Fallback scan over the document list when a query term is not in the vocabulary.",
    },
    {
        "id": "binary_search",
        "name": "Binary Search",
        "category": "Searching",
        "purpose": "Locate a key in a sorted sequence by repeatedly halving the range.",
        "input": "Sorted list + target key",
        "output": "Index of the match, or not-found",
        "time": "O(log n)",
        "space": "O(1) iterative / O(log n) recursive",
        "best": "O(1) - found on the first probe",
        "average": "O(log n)",
        "worst": "O(log n) - floor(log2 n) + 1 probes",
        "why": "Halving the search interval each step gives an exponential decay of the candidate set.",
        "used_for": "Binary-searching sorted document-id / score arrays (lookups by id, threshold filters).",
    },
    {
        "id": "hash_search",
        "name": "Hash Search",
        "category": "Searching",
        "purpose": "Map keywords to document postings with a hash function + collision handling.",
        "input": "Key string",
        "output": "Value (posting list / document record)",
        "time": "O(1) average, O(n) worst",
        "space": "O(n)",
        "best": "O(1)",
        "average": "O(1) when load factor alpha <= 0.75",
        "worst": "O(n) - every key lands in one bucket",
        "why": "Turns key lookup into address arithmetic instead of comparison, so the cost stops depending on n.",
        "used_for": "keyword -> posting list map, O(1) document lookup by id, duplicate detection on import.",
    },
    {
        "id": "trie_search",
        "name": "Trie Search (Prefix Tree)",
        "category": "Searching",
        "purpose": "Dictionary + prefix lookup over strings in O(word length).",
        "input": "Word or prefix",
        "output": "Membership, posting list, or all words under a prefix",
        "time": "O(L) exact / O(L + P) prefix",
        "space": "O(total characters)",
        "best": "O(L)",
        "average": "O(L)",
        "worst": "O(L) - L independent of dictionary size",
        "why": "Prefixes share path nodes, so no comparison against the whole vocabulary is ever needed.",
        "used_for": "Vocabulary checks, type-ahead autocomplete, phrase walks during query analysis.",
    },
    # --------------------------------------------------------- string matching
    {
        "id": "kmp",
        "name": "KMP String Matching",
        "category": "String Matching",
        "purpose": "Find all occurrences of a pattern in a text in linear time.",
        "input": "Text (n) and pattern (m)",
        "output": "List of match start positions + LPS array",
        "time": "O(n + m)",
        "space": "O(m)",
        "best": "O(n)",
        "average": "O(n + m)",
        "worst": "O(n + m) - no re-scan of the text",
        "why": "The LPS array tells the matcher how much of the matched prefix to keep after a mismatch.",
        "used_for": "Exact-phrase detection in document bodies (quoted queries).",
    },
    {
        "id": "rabin_karp",
        "name": "Rabin-Karp String Matching",
        "category": "String Matching",
        "purpose": "Rolling-hash pre-filter, then verify candidate windows.",
        "input": "Text (n) and pattern (m)",
        "output": "Match positions + number of hash collisions handled",
        "time": "O(n + m) average, O(n*m) worst",
        "space": "O(1) auxiliary (single window)",
        "best": "O(n)",
        "average": "O(n + m)",
        "worst": "O(n * m) - every window hash collides",
        "why": "Recomputes each window hash in O(1), which also lets one pass screen many patterns.",
        "used_for": "Cross-checking KMP results and multi-pattern phrase screening in the phrase scanner.",
    },
    # ----------------------------------------------------------------- sorting
    {
        "id": "merge_sort",
        "name": "Merge Sort",
        "category": "Sorting",
        "purpose": "Stable divide & conquer sort with a guaranteed n log n bound.",
        "input": "Unsorted list",
        "output": "Sorted list",
        "time": "Theta(n log n)",
        "space": "Theta(n)",
        "best": "Theta(n log n)",
        "average": "Theta(n log n)",
        "worst": "Theta(n log n)",
        "why": "The merge step is linear and halves the problem twice per level -> n log n for every input shape.",
        "used_for": "Ordering search results by relevance score (stable tie-breaks).",
    },
    {
        "id": "quick_sort",
        "name": "Quick Sort",
        "category": "Sorting",
        "purpose": "In-place divide & conquer sort, cache-friendly and very fast in practice.",
        "input": "Unsorted list",
        "output": "Sorted list",
        "time": "Theta(n log n) average, Theta(n^2) worst",
        "space": "O(log n) expected",
        "best": "Theta(n log n)",
        "average": "Theta(n log n)",
        "worst": "Theta(n^2) - bad pivot every partition",
        "why": "Partitioning is linear and the pivot split is usually balanced; median-of-three avoids the sorted-input trap.",
        "used_for": "Alternative result ordering + the sorting benchmark comparison.",
    },
    {
        "id": "heap_sort",
        "name": "Heap Sort",
        "category": "Sorting",
        "purpose": "In-place sort by repeatedly extracting the maximum of a binary heap.",
        "input": "Unsorted list",
        "output": "Sorted list",
        "time": "Theta(n log n)",
        "space": "O(1)",
        "best": "Theta(n log n)",
        "average": "Theta(n log n)",
        "worst": "Theta(n log n)",
        "why": "Build-heap is O(n) by Floyd's method, then n extract-mins at O(log n) each.",
        "used_for": "Priority scheduling of the document traversal frontier.",
    },
    # ------------------------------------------------------------------ graph
    {
        "id": "bfs",
        "name": "BFS (Breadth-First Search)",
        "category": "Graph",
        "purpose": "Level-by-level traversal; shortest path by number of edges.",
        "input": "Adjacency list + start node",
        "output": "Level order, parents, shortest path",
        "time": "O(V + E)",
        "space": "O(V)",
        "best": "O(V)",
        "average": "O(V + E)",
        "worst": "O(V + E)",
        "why": "FIFO queue processes vertices in non-decreasing distance, so the first path found is shortest.",
        "used_for": "\"Related documents\" within k hops, level display on the graph page.",
    },
    {
        "id": "dfs",
        "name": "DFS (Depth-First Search)",
        "category": "Graph",
        "purpose": "Go deep along one branch, then backtrack.",
        "input": "Adjacency list + start node",
        "output": "Pre-order, parents, back-edge (cycle) information",
        "time": "O(V + E)",
        "space": "O(V)",
        "best": "O(V)",
        "average": "O(V + E)",
        "worst": "O(V + E)",
        "why": "LIFO stack (or recursion) exhausts a subtree before moving on; recursion depth can reach V.",
        "used_for": "Related-document deep dives, connected components, cycle detection.",
    },
    {
        "id": "dijkstra",
        "name": "Dijkstra's Algorithm",
        "category": "Graph",
        "purpose": "Shortest paths from one source with non-negative edge weights.",
        "input": "Weighted adjacency list + source",
        "output": "Distance labels, parents, shortest path tree",
        "time": "O((V + E) log V)",
        "space": "O(V)",
        "best": "O((V + E) log V)",
        "average": "O((V + E) log V)",
        "worst": "O((V + E) log V)",
        "why": "Priority queue extracts the closest unsettled node; the greedy step is safe for non-negative weights.",
        "used_for": "Weighted document similarity paths (shared keywords = edge weight).",
    },
    {
        "id": "pagerank",
        "name": "PageRank",
        "category": "Ranking",
        "purpose": "Link-analysis authority score, independent of the query.",
        "input": "Directed link graph",
        "output": "Per-document authority probability",
        "time": "O(I * (V + E))",
        "space": "O(V + E)",
        "best": "~25-40 iterations for 1e-6 on our corpus",
        "average": "O(40 * (V + E))",
        "worst": "O(I_max * (V + E))",
        "why": "A page is important if important pages link to it; damping models the random surfer.",
        "used_for": "GraphScore signal in the final relevance formula (pre-computed, cached).",
    },
    # --------------------------------------------------------------- ranking
    {
        "id": "tfidf",
        "name": "TF-IDF Retrieval",
        "category": "Ranking",
        "purpose": "Score documents by term rarity x term frequency, compared with cosine similarity.",
        "input": "Tokenised query + tokenised corpus",
        "output": "Per-document cosine score",
        "time": "O(total tokens) to build, O(sum of postings) per query",
        "space": "O(vocabulary)",
        "best": "O(k + df) for k query terms",
        "average": "O(k * df)",
        "worst": "O(V * L) if every document contains every term",
        "why": "IDF discounts terms that appear everywhere; cosine removes the document-length bias.",
        "used_for": "ContentScore signal (0.20 weight) in the ranking formula.",
    },
    {
        "id": "relevance_ranking",
        "name": "Weighted Relevance Ranking",
        "category": "Ranking",
        "purpose": "Fuse title, keyword, content, phrase and graph signals into one score.",
        "input": "Candidate documents + per-signal values",
        "output": "Sorted result list with a full score breakdown",
        "time": "O(n log n) (Merge Sort on the candidates)",
        "space": "O(n)",
        "best": "O(n log n)",
        "average": "O(n log n)",
        "worst": "O(n log n)",
        "why": "Each signal alone is misleading; a weighted sum with interpretable parts is explainable to a user.",
        "used_for": "Final ordering of search results.",
    },
    {
        "id": "binary_heap",
        "name": "Binary Heap / Priority Queue",
        "category": "Data Structures",
        "purpose": "Insert / extract-min in O(log n) - the priority queue behind Dijkstra.",
        "input": "Priority-value pairs",
        "output": "Minimum element (pop) or updated heap",
        "time": "O(log n) push/pop, O(1) peek, O(n) build",
        "space": "O(n)",
        "best": "O(1) peek",
        "average": "O(log n)",
        "worst": "O(log n)",
        "why": "A complete binary tree in a flat array lets us walk up/down with index arithmetic only.",
        "used_for": "Dijkstra's frontier queue.",
    },
]

COMPLEXITY_CLASSES = [
    {"symbol": "O(1)", "name": "Constant", "example": "Array index, hash table lookup (average)",
     "grows": False, "algorithms": ["Hash Search (average)", "Heap peek", "Binary Search best case"]},
    {"symbol": "O(log n)", "name": "Logarithmic", "example": "Binary search, balanced BST, Floyd heapify",
     "grows": False, "algorithms": ["Binary Search", "Merge Sort (per level)", "Heap operations"]},
    {"symbol": "O(n)", "name": "Linear", "example": "Linear search, BFS, DFS, KMP, Merge Sort (per level)",
     "grows": True, "algorithms": ["Linear Search", "BFS", "DFS", "KMP", "Rabin-Karp (filter)"]},
    {"symbol": "O(n log n)", "name": "Linearithmic", "example": "Merge Sort, Quick Sort (average), Heap Sort",
     "grows": True, "algorithms": ["Merge Sort", "Quick Sort", "Heap Sort", "Dijkstra", "Relevance Ranking"]},
    {"symbol": "O(n^2)", "name": "Quadratic", "example": "Naive string matching, bubble/selection sort, bad-pivot Quick Sort",
     "grows": True, "algorithms": ["Naive matcher", "Quick Sort worst case", "Insertion Sort"]},
    {"symbol": "O(2^n)", "name": "Exponential", "example": "Naive subset enumeration, naive recursion without memoisation",
     "grows": True, "algorithms": ["Brute-force permutations", "Un-memoised Fibonacci"]},
]

CATEGORIES = ["Searching", "String Matching", "Sorting", "Graph", "Ranking", "Data Structures"]


def get_algorithm(algorithm_id: str) -> dict | None:
    for entry in ALGORITHMS:
        if entry["id"] == algorithm_id:
            return entry
    return None


def by_category() -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = {}
    for entry in ALGORITHMS:
        grouped.setdefault(entry["category"], []).append(entry)
    return grouped


def all_ids() -> list[str]:
    return [entry["id"] for entry in ALGORITHMS]
